{% set version = "1.1.0" %}

package:
  name: macha
  version: 0.1

source:
  git_url: https://github.com/akaupang/macha.git
  
requirements:
  build:
    - python
    - setuptools
    
  
  script: python devtools/setup.py install
    


